# Generated by Django 5.1.1 on 2024-09-20 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("APARTMENT", "דירה"),
                            ("VILLA", "וילה"),
                            ("LOT", "מגרש"),
                        ],
                        default="APARTMENT",
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField()),
                ("square_meters", models.PositiveIntegerField()),
                ("num_rooms", models.PositiveSmallIntegerField(default=1)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("is_available", models.BooleanField(default=True)),
                ("elevator", models.BooleanField(default=False)),
                ("parking", models.BooleanField(default=False)),
                ("balcony", models.BooleanField(default=False)),
                ("mamad", models.BooleanField(default=False)),
                ("air_conditioning", models.BooleanField(default=False)),
                ("sun_boiler", models.BooleanField(default=False)),
                ("storage", models.BooleanField(default=False)),
                ("renovated", models.BooleanField(default=False)),
                ("access_for_disabled", models.BooleanField(default=False)),
                (
                    "num_floors_in_building",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("floor_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "avg_annual_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "avg_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="property_images/"
                    ),
                ),
                ("neighborhood_score", models.JSONField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date_invested", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "referral_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to="main.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "רגיל"),
                            ("PREMIUM", "פרימיום"),
                            ("BROKER", "מתווך"),
                            ("ADMIN", "מנהל מערכת"),
                        ],
                        default="REGULAR",
                        max_length=10,
                    ),
                ),
                ("identification_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
